### ISSUE TITLE
fluid pipes are not craftable (?)

### ISSUE THREAD

**Issue by shirikan** [Fabricators-of-Create/Create#1658]
### Description

i'm quite new to create and have recently started my first survival world with it with this fabric port, the problem has come when i started wanting to automate certain actions with fluids but needed pipes, obviously. i looked up the recipe for pipes since i never got the recipe in-game and i dont know why, anyway the recipe did not work, not even with mechanical crafters... the recipe was two copper sheets and a copper ingot in the middle, of course, but it doesnt work. i even tried loading up another world but the problem seems to be global, i really dont know why im the first to report this issue but it may be a bug correlated to other mods i guess (which in my case are: "carryon", "create jetpack" (might be the culprit ig idk), "fabric language kotlin", "indium", "sodium", "sophisticated backpacks (unofficial fabric port)", "sophisticated core (unofficial fabric port)" and finally "jade") i am extremely confused on why fluid pipes of all things are seemingly not craftable in survival. help me please i wanna play create its a really cool mod, also thank you all for this fabric port you made!!
p.s. i literally made this github account only for this lol
p.p.s. hope i reported right let me know if you need anything else thank you byeee

### Game Log

https://mclo.gs/rMNmfly

### Debug Information

<details>
<summary>Client Info</summary>

```
Create:
	Mod Version: 0.5.1j
	Fabric API Version: 0.92.2+1.20.1
	Minecraft Version: 1.20.1

Graphics:
	Flywheel Version: 0.6.11-4
	Flywheel Backend: INSTANCING
	OpenGL Renderer: Intel(R) HD Graphics 610
	OpenGL Version: 3.2.0 - Build 27.20.100.8682
	Graphics Mode: options.graphics.fancy

System Information:
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Memory: 1080014128 bytes (1029 MiB) / 2311061504 bytes (2204 MiB) up to 4294967296 bytes (4096 MiB)
	Total Memory: 3880824832 bytes (3699 MiB) / 4172345344 bytes (3977 MiB)
	CPU: Intel(R) Pentium(R) CPU 4415U @ 2.30GHz @ 2.30 GHz; 2 cores / 4 threads on 1 socket(s)
	Graphics card #0: Intel(R) HD Graphics 610 (Intel Corporation (0x8086)); 1024.00 MB of VRAM

Other Mods:
	Carry On: 2.1.2.7
	core: 3.6.6
	toml: 3.6.6
	jsr305: 3.0.2
	Create Jetpack: 4.2.1
	Dripstone Fluid Lib: 3.0.2
	Fabric API Base: 0.4.31+1802ada577
	Fabric API Lookup API (v1): 1.6.36+1802ada577
	Fabric Biome API (v1): 13.0.13+1802ada577
	Fabric Block API (v1): 1.0.11+1802ada577
	Fabric BlockView API (v2): 1.0.1+1802ada577
	Fabric BlockRenderLayer Registration (v1): 1.1.41+1802ada577
	Fabric Client Tags: 1.1.2+1802ada577
	Fabric Command API (v1): 1.2.34+f71b366f77
	Fabric Command API (v2): 2.2.13+1802ada577
	Fabric Commands (v0): 0.2.51+df3654b377
	Fabric Containers (v0): 0.1.64+df3654b377
	Fabric Content Registries (v0): 4.0.11+1802ada577
	Fabric Convention Tags: 1.5.5+1802ada577
	Fabric Crash Report Info (v1): 0.2.19+1802ada577
	Fabric Data Attachment API (v1): 1.0.0+de0fd6d177
	Fabric Data Generation API (v1): 12.3.4+1802ada577
	Fabric Dimensions API (v1): 2.1.54+1802ada577
	Fabric Entity Events (v1): 1.6.0+1c78457f77
	Fabric Events Interaction (v0): 0.6.2+1802ada577
	Fabric Events Lifecycle (v0): 0.2.63+df3654b377
	Fabric Game Rule API (v1): 1.0.40+1802ada577
	Fabric Item API (v1): 2.1.28+1802ada577
	Fabric Item Group API (v1): 4.0.12+1802ada577
	Fabric Key Binding API (v1): 1.0.37+1802ada577
	Fabric Key Bindings (v0): 0.2.35+df3654b377
	Fabric Language Kotlin: 1.13.0+kotlin.2.1.0
	Fabric Lifecycle Events (v1): 2.2.22+1802ada577
	Fabric Loot API (v2): 1.2.1+1802ada577
	Fabric Loot Tables (v1): 1.1.45+9e7660c677
	Fabric Message API (v1): 5.1.9+1802ada577
	Fabric Mining Level API (v1): 2.1.50+1802ada577
	Fabric Model Loading API (v1): 1.0.3+1802ada577
	Fabric Models (v0): 0.4.2+9386d8a777
	Fabric Networking API (v1): 1.3.11+1802ada577
	Fabric Networking (v0): 0.3.51+df3654b377
	Fabric Object Builder API (v1): 11.1.3+1802ada577
	Fabric Particles (v1): 1.1.2+1802ada577
	Fabric Recipe API (v1): 1.0.21+1802ada577
	Fabric Registry Sync (v0): 2.3.3+1802ada577
	Fabric Renderer API (v1): 3.2.1+1802ada577
	Fabric Renderer - Indigo: 1.5.2+85287f9f77
	Fabric Renderer Registries (v1): 3.2.46+df3654b377
	Fabric Rendering Data Attachment (v1): 0.3.37+92a0d36777
	Fabric Rendering Fluids (v1): 3.0.28+1802ada577
	Fabric Rendering (v0): 1.1.49+df3654b377
	Fabric Rendering (v1): 3.0.8+1802ada577
	Fabric Resource Conditions API (v1): 2.3.8+1802ada577
	Fabric Resource Loader (v0): 0.11.10+1802ada577
	Fabric Screen API (v1): 2.0.8+1802ada577
	Fabric Screen Handler API (v1): 1.3.30+1802ada577
	Fabric Sound API (v1): 1.0.13+1802ada577
	Fabric Transfer API (v1): 3.3.5+8dd72ea377
	Fabric Transitive Access Wideners (v1): 4.3.1+1802ada577
	Fabric Loader: 0.16.9
	Flight Lib: 2.1.0
	Forge Config API Port: 8.0.0
	Indium: 1.0.34+mc1.20.1
	OpenJDK 64-Bit Server VM: 17
	Milk Lib: 1.2.60
	MixinExtras: 0.4.1
	kotlin-reflect: 2.1.0
	kotlin-stdlib: 2.1.0
	kotlin-stdlib-jdk7: 2.1.0
	kotlin-stdlib-jdk8: 2.1.0
	atomicfu-jvm: 0.26.1
	kotlinx-coroutines-core-jvm: 1.9.0
	kotlinx-coroutines-jdk8: 1.9.0
	kotlinx-datetime-jvm: 0.6.1
	kotlinx-io-bytestring-jvm: 0.6.0
	kotlinx-io-core-jvm: 0.6.0
	kotlinx-serialization-cbor-jvm: 1.7.3
	kotlinx-serialization-core-jvm: 1.7.3
	kotlinx-serialization-json-jvm: 1.7.3
	Porting Lib Accessors: 2.3.8+1.20.1
	Porting Lib Attributes: 2.3.8+1.20.1
	Porting Lib Base: 2.3.8+1.20.1
	Porting Lib Brewing: 2.3.8+1.20.1
	Porting Lib Client Events: 2.3.8+1.20.1
	Porting Lib Common: 2.3.8+1.20.1
	Porting Lib Config: 2.3.8+1.20.1
	Porting Lib Core: 2.3.8+1.20.1
	Porting Lib Data: 2.1.1090+1.20
	Porting Lib Entity: 2.3.8+1.20.1
	Porting Lib Extensions: 2.3.8+1.20.1
	Porting Lib Fluids: 2.3.8+1.20.1
	Porting Lib GameTest: 2.1.1090+1.20
	Porting Lib Gui Utils: 2.3.8+1.20.1
	Porting Lib Lazy Register: 2.3.8+1.20.1
	Porting Lib Loot: 2.3.2+1.20.1
	Porting Lib Mixin Extensions: 2.3.8+1.20.1
	Porting Lib Model Generators: 2.1.1090+1.20
	Porting Lib Model Loader: 2.3.8+1.20.1
	Porting Lib Model Materials: 2.1.1090+1.20
	Porting Lib Models: 2.3.8+1.20.1
	Porting Lib Networking: 2.3.8+1.20.1
	Porting Lib Obj Loader: 2.3.8+1.20.1
	Porting Lib Tags: 3.0
	Porting Lib Tool Actions: 2.3.8+1.20.1
	Porting Lib Transfer: 2.3.8+1.20.1
	Porting Lib Utility: 2.3.8+1.20.1
	Reach Entity Attributes: 2.4.0
	Registrate for Fabric: 1.3.79-MC1.20.1
	Sodium: 0.5.11+mc1.20.1
	Sophisticated Backpacks: 1.20.1-3.20.11.26
	Sophisticated Core: 1.20.1-0.6.35.49
	Energy: 3.0.0
```

</details>

<details>
<summary>Server Info</summary>

```
Create:
	Mod Version: 0.5.1j
	Fabric API Version: 0.92.2+1.20.1
	Minecraft Version: 1.20.1

System Information:
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Memory: 1080014128 bytes (1029 MiB) / 2311061504 bytes (2204 MiB) up to 4294967296 bytes (4096 MiB)
	Total Memory: 3880824832 bytes (3699 MiB) / 4172345344 bytes (3977 MiB)
	CPU: Intel(R) Pentium(R) CPU 4415U @ 2.30GHz @ 2.30 GHz; 2 cores / 4 threads on 1 socket(s)
	Graphics card #0: Intel(R) HD Graphics 610 (Intel Corporation (0x8086)); 1024.00 MB of VRAM

Other Mods:
	Carry On: 2.1.2.7
	core: 3.6.6
	toml: 3.6.6
	jsr305: 3.0.2
	Create Jetpack: 4.2.1
	Dripstone Fluid Lib: 3.0.2
	Fabric API Base: 0.4.31+1802ada577
	Fabric API Lookup API (v1): 1.6.36+1802ada577
	Fabric Biome API (v1): 13.0.13+1802ada577
	Fabric Block API (v1): 1.0.11+1802ada577
	Fabric BlockView API (v2): 1.0.1+1802ada577
	Fabric BlockRenderLayer Registration (v1): 1.1.41+1802ada577
	Fabric Client Tags: 1.1.2+1802ada577
	Fabric Command API (v1): 1.2.34+f71b366f77
	Fabric Command API (v2): 2.2.13+1802ada577
	Fabric Commands (v0): 0.2.51+df3654b377
	Fabric Containers (v0): 0.1.64+df3654b377
	Fabric Content Registries (v0): 4.0.11+1802ada577
	Fabric Convention Tags: 1.5.5+1802ada577
	Fabric Crash Report Info (v1): 0.2.19+1802ada577
	Fabric Data Attachment API (v1): 1.0.0+de0fd6d177
	Fabric Data Generation API (v1): 12.3.4+1802ada577
	Fabric Dimensions API (v1): 2.1.54+1802ada577
	Fabric Entity Events (v1): 1.6.0+1c78457f77
	Fabric Events Interaction (v0): 0.6.2+1802ada577
	Fabric Events Lifecycle (v0): 0.2.63+df3654b377
	Fabric Game Rule API (v1): 1.0.40+1802ada577
	Fabric Item API (v1): 2.1.28+1802ada577
	Fabric Item Group API (v1): 4.0.12+1802ada577
	Fabric Key Binding API (v1): 1.0.37+1802ada577
	Fabric Key Bindings (v0): 0.2.35+df3654b377
	Fabric Language Kotlin: 1.13.0+kotlin.2.1.0
	Fabric Lifecycle Events (v1): 2.2.22+1802ada577
	Fabric Loot API (v2): 1.2.1+1802ada577
	Fabric Loot Tables (v1): 1.1.45+9e7660c677
	Fabric Message API (v1): 5.1.9+1802ada577
	Fabric Mining Level API (v1): 2.1.50+1802ada577
	Fabric Model Loading API (v1): 1.0.3+1802ada577
	Fabric Models (v0): 0.4.2+9386d8a777
	Fabric Networking API (v1): 1.3.11+1802ada577
	Fabric Networking (v0): 0.3.51+df3654b377
	Fabric Object Builder API (v1): 11.1.3+1802ada577
	Fabric Particles (v1): 1.1.2+1802ada577
	Fabric Recipe API (v1): 1.0.21+1802ada577
	Fabric Registry Sync (v0): 2.3.3+1802ada577
	Fabric Renderer API (v1): 3.2.1+1802ada577
	Fabric Renderer - Indigo: 1.5.2+85287f9f77
	Fabric Renderer Registries (v1): 3.2.46+df3654b377
	Fabric Rendering Data Attachment (v1): 0.3.37+92a0d36777
	Fabric Rendering Fluids (v1): 3.0.28+1802ada577
	Fabric Rendering (v0): 1.1.49+df3654b377
	Fabric Rendering (v1): 3.0.8+1802ada577
	Fabric Resource Conditions API (v1): 2.3.8+1802ada577
	Fabric Resource Loader (v0): 0.11.10+1802ada577
	Fabric Screen API (v1): 2.0.8+1802ada577
	Fabric Screen Handler API (v1): 1.3.30+1802ada577
	Fabric Sound API (v1): 1.0.13+1802ada577
	Fabric Transfer API (v1): 3.3.5+8dd72ea377
	Fabric Transitive Access Wideners (v1): 4.3.1+1802ada577
	Fabric Loader: 0.16.9
	Flight Lib: 2.1.0
	Forge Config API Port: 8.0.0
	Indium: 1.0.34+mc1.20.1
	OpenJDK 64-Bit Server VM: 17
	Milk Lib: 1.2.60
	MixinExtras: 0.4.1
	kotlin-reflect: 2.1.0
	kotlin-stdlib: 2.1.0
	kotlin-stdlib-jdk7: 2.1.0
	kotlin-stdlib-jdk8: 2.1.0
	atomicfu-jvm: 0.26.1
	kotlinx-coroutines-core-jvm: 1.9.0
	kotlinx-coroutines-jdk8: 1.9.0
	kotlinx-datetime-jvm: 0.6.1
	kotlinx-io-bytestring-jvm: 0.6.0
	kotlinx-io-core-jvm: 0.6.0
	kotlinx-serialization-cbor-jvm: 1.7.3
	kotlinx-serialization-core-jvm: 1.7.3
	kotlinx-serialization-json-jvm: 1.7.3
	Porting Lib Accessors: 2.3.8+1.20.1
	Porting Lib Attributes: 2.3.8+1.20.1
	Porting Lib Base: 2.3.8+1.20.1
	Porting Lib Brewing: 2.3.8+1.20.1
	Porting Lib Client Events: 2.3.8+1.20.1
	Porting Lib Common: 2.3.8+1.20.1
	Porting Lib Config: 2.3.8+1.20.1
	Porting Lib Core: 2.3.8+1.20.1
	Porting Lib Data: 2.1.1090+1.20
	Porting Lib Entity: 2.3.8+1.20.1
	Porting Lib Extensions: 2.3.8+1.20.1
	Porting Lib Fluids: 2.3.8+1.20.1
	Porting Lib GameTest: 2.1.1090+1.20
	Porting Lib Gui Utils: 2.3.8+1.20.1
	Porting Lib Lazy Register: 2.3.8+1.20.1
	Porting Lib Loot: 2.3.2+1.20.1
	Porting Lib Mixin Extensions: 2.3.8+1.20.1
	Porting Lib Model Generators: 2.1.1090+1.20
	Porting Lib Model Loader: 2.3.8+1.20.1
	Porting Lib Model Materials: 2.1.1090+1.20
	Porting Lib Models: 2.3.8+1.20.1
	Porting Lib Networking: 2.3.8+1.20.1
	Porting Lib Obj Loader: 2.3.8+1.20.1
	Porting Lib Tags: 3.0
	Porting Lib Tool Actions: 2.3.8+1.20.1
	Porting Lib Transfer: 2.3.8+1.20.1
	Porting Lib Utility: 2.3.8+1.20.1
	Reach Entity Attributes: 2.4.0
	Registrate for Fabric: 1.3.79-MC1.20.1
	Sodium: 0.5.11+mc1.20.1
	Sophisticated Backpacks: 1.20.1-3.20.11.26
	Sophisticated Core: 1.20.1-0.6.35.49
	Energy: 3.0.0
```

</details>

**Comment by IThundxr** [comment]
Update create

**Comment by shirikan** [comment]
i cant update it (to add info, i use curseforge)

**Comment by kxdxzr** [comment]
Hi shirikan,

I found the Fluid Tank craft table is missing today and seek for any updates available and found that it is fixed in the latest version published **yesterday**.

Best regards,
kxdxzr

**Comment by shirikan** [comment]
ok, thank you for your patience, i found out that curseforge did not tell me that a new update was there until i searched for it, but the bug persists and curseforge still tells me i should update create to a build old of months rather than the most recent one, i might be doing something wrong since i dont have much knowledge of minecraft java and curseforge and everything else. sorry if im an annoyance but i hope you can further help me.

**Comment by IThundxr** [comment]
If curseforge isn't displaying the file correctly then grab it from modrinth https://modrinth.com/mod/create-fabric/version/0.5.1-j-build.1609+mc1.20.1

**Comment by shirikan** [comment]
i dont know if its right but i moved the download of modrinth to the minecraft mods folder searching in the start menu the %appdata% folder but it didnt work. coming back to curseforge i have noticed how it asks you to update to a specific build which is the 12/1/24 one while the most recent i see is the 3/9/24 one which is also not yesterday, could it be that i need to update curseforge? if yes, how?

**Comment by shirikan** [comment]
i just now moved the download of modrinth in the curseforge folder which i believe correct. hope this will work.

**Comment by shirikan** [comment]
it works!!!!!!!!!!!!!!
thank you for your time and advice
