### ISSUE TITLE
Crash when attempting to use SchematicCannon(creative or survival) or schematics in creative

### ISSUE THREAD

**Issue by weegeeluigi** [Fabricators-of-Create/Create#260]
### Describe the Bug

When attempting to use the schematic cannon in any game mode, or when attempting to use a schematic in creative to instantly place, it insta crashes.  

For the schematic cannon this happens even when just placing the schematic in it and a book, trying to get the materials list.

For a schematic the moment you try to instantly place it in creative it crashes.  The error is the same for both, so including the log for when the cannon crashes.

Using latest build#514

### Reproduction Steps

1.Place schematic cannon
2.Get a schematic
3. Put the schematic in the cannon with a book
4.  Try getting the materials list and it should crash.
5.  It should also crash if you have items in the chest, and you activate it

### Expected Result

SchematicCannon places blocks

### Crash Report or Log

https://gist.github.com/weegeeluigi/a378b8e744a0115e4b84e7d7b034fa14

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

**Comment by TropheusJ** [comment]
This should be fixed, please test it and re-open if it persists.

**Comment by weegeeluigi** [comment]
Hey @TropheusJ , just wanted to let you know this can stay closed.  It still crashed on build #520 but I created my own, brand new schematic and it worked fine.  The ones that crashed I last used just fine on #494 prior to 1.18.2 so it's possible they are just no longer compatible.
