### ISSUE TITLE
Andesite funnel & chute cannot pull from some Modern Industrialization machines unless inputs are empty 

### ISSUE THREAD

**Issue by saltyseadoggo** [Fabricators-of-Create/Create#408]
### Describe the Bug

Create's andesite funnel and chute cannot extract items from the output slots of several Modern Industrialization machines, notably the furnaces, macerators, mixers, and compressors, unless their input slots are empty. For example, if you place a Steel Mixer above a Chute, provide it steam, and have it process Copper and Tin Dust into Bronze Dust, the chute should extract and spit out the bronze dust as they're made, but, instead, it won't spit out the bronze dust until the copper and tin dust are consumed in crafting or removed by a player.
Changing the "Item Auto-Extraction" setting in the machine's interface and changing the side with the black square on it both have no effect on this issue.

The brass funnel and smart chute can extract from MI's machines, but only if they are given a filter item and the item in the output slot(s) matches it.

I would like to see this fixed so that Create chutes and funnels take items from MI machines' output slots to spit out, regardless of what's in the input slots.

### Reproduction Steps

1. Start a new world in creative mode.
2. Obtain these items:
Chute
Steel Mixer (MI)
64x Copper Dust (MI)
64x Tin Dust (MI)
Fluid pipes from either mod
Steam Bucket (MI)
A creative tank from either mod
3. Place the chute, then place the steel mixer above it.
4. Place the creative tank, then connect it to the steel mixer with pipes from either mod.
5. Right click the tank with the steam bucket to fill it with steam.
6. Right click the mixer.
7. Add the copper and tin dusts to the input slot, and watch as they are turned into bronze dust.
8. Observe how the chute does not extract the bronze dust.
9. Remove all items from the input slots, and observe how the chute now extracts the bronze dust.

### Expected Result

Chutes, andesite funnels, and smart chutes/brass funnels without a filter item should be able to pull from the output slot of MI machines while there are items in the input slots.

### Operating System

Ubuntu Focal

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

Fabric API 0.57.0
Cloth Config 6.2.62
Architectury 4.5.75
Roughly Enough Items 8.3.501
Modern Industrialization 1.2.1

### Additional Context

The matching issue on the Modern Industrialization repo, with Technici4n's response:
https://github.com/AztechMC/Modern-Industrialization/issues/354

**Comment by CzechHek** [comment]
#389

**Comment by TropheusJ** [comment]
this is likely fixed in dev, re-open if it persists

**Comment by Strubbelkopp** [comment]
The problem still exists. Tested it on 1.19.2 and 1.20.1.
In 1.20.1 I'm using version 0.5.1-d-build.1161 of Create and version 1.7.3 of Modern Industrialization
