### ISSUE TITLE
texture bug with liquid pipes

### ISSUE THREAD

**Issue by Guppy3874** [Fabricators-of-Create/Create#453]
### Describe the Bug

If you build a section with a few pipes and look at them from a little higher up, they become invisible.

### Reproduction Steps

1. build a 4 block long pipe
2. look at them from a certain angle
...

### Expected Result

normal looking pipes from all angles

### Screenshots and Videos

![2022-07-24_22 19 39](https://user-images.githubusercontent.com/98043898/180664624-78d5d0a6-3535-4827-bdf9-d317f83f3a6c.png)

### Operating System

Windows 11

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

Terra (Worldgeneration) 6.0.0
Sodium 0.4.1
Indium 1.0.6
Fabric API 0.58.0
Create 0.5.0c build 683

**Comment by AlphaMode** [comment]
This has already been fixed in later builds please update

**Comment by TropheusJ** [comment]
This is a sodium issue and needs further investigation, it's not fixed

**Comment by buerrebones** [comment]
after thorough testing, the cause for this issue seems to have something to do with chunk boundaries:

When first loading up a world, vertical pipes start to glitch if the player's y value meets or _exceeds_ the y value of the tallest pipe—viewing from below the lowest pipe doesn't have the same effect. This specific cause is inconsistent, though. The prevailing cause for Y-aligned pipes is viewing them from different vertical subchunks; any pipes located outside of the subchunk the player is currently in will glitch.

Horizontal pipes facing positive or negative X glitch when the player steps into a chunk towards positive or negative X; the same applies to pipes facing Z, respectively. this means that stepping into a chunk towards positive Z causes Z-aligned pipes to glitch, but not X-aligned pipes. It's weird.

I should also note: pushing the player _against_ (not past) the chunk boundary facing positive X or Z causes the visual glitch to occur. This also happens when pushed against negative X or Z, but only if the player is located 1 block _past_ the chunk boundary. Same applies for subchunks with Y-aligned pipes (crouching on top of the boundary causes it)

there are a lot of other inconsistent conditions that also cause it from what i've found, but the above are the most reliable and easily replicable.

this is all on the latest build at the time (0.5.0c-708, "bump EMI" build), with only fabric API, sodium, and indium installed.

**Comment by Guppy3874** [comment]
seems fixed in the newest public release
