### ISSUE TITLE
Pumping lava is not continuous or infinite

### ISSUE THREAD

**Issue by 404Mate** [Fabricators-of-Create/Create#492]
### Describe the Bug

When I try to pump lava it is no longer a continuous flow and keeps on getting reset as if it stopped pumping.

### Reproduction Steps

1. Setup a hose connected to an infinite lava source with a pump
2. Power the pump

### Expected Result

Pumping lava would be continuous

### Operating System

Windows 11

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

  [✔️] [Fabric]+Wildfire+Female+Gender+Mod-2.9.jar
  [✔️] 3dskinlayers-fabric-1.4.6-mc1.18.2(1).jar
  [✔️] AdditionalBanners-Fabric-1.18.2-7.0.6.jar
  [✔️] Adorn-3.5.0+1.18.2-fabric.jar
  [✔️] appleskin-fabric-mc1.18.2-2.4.0.jar
  [✔️] architectury-4.7.78-fabric.jar
  [✔️] axolotl-item-fix-1.1.3 (2).jar
  [✔️] badpackets-fabric-0.1.2 (1).jar
  [✔️] bedspreads-fabric-1.6.0-1.18.jar
  [✔️] blockus-2.4.7+1.18.2.jar
  [✔️] Bookshelf-Fabric-1.18.2-13.2.21.jar
  [✔️] clickadv-fabric-2.6.jar
  [✔️] clickthrough-1.18.2-fabric0.47.10-0.4.jar
  [✔️] cloth-config-6.2.62-fabric.jar
  [✔️] collective-fabric-1.18.2-4.36.jar
  [✔️] continuity-2.0.0+1.18.2.jar
  [✔️] Cosmetica+1.18.2+1.1.1.jar
  [✔️] create-1.18.2-0.5.0c-708.jar
  [✔️] Croptopia-1.18.2-FABRIC-2.0.5.jar
  [✔️] DarkPaintings-Fabric-1.18.2-10.0.3.jar
  [✔️] doubledoors-fabric_1.18.2-3.6.jar
  [✔️] dual_riders-1.18.2-1.1.1-fabric.jar
  [✔️] duckling-1.0.5-fabric.jar
  [✔️] easiervillagertrading-1.18.2-fabric0.47.10-1.5.4.jar
  [✔️] EmeraldTools-Fabric-1.18.2-1.3.47.jar
  [✔️] extraorigins-1.18-11.jar
  [✔️] fabric-api-0.58.0+1.18.2.jar
  [✔️] fabric-language-kotlin-1.8.2+kotlin.1.7.10.jar
  [✔️] feature_nbt_deadlock_be_gone_fabric-2.0.0+1.18.2-rc1.jar
  [✔️] flytre_lib-1.18.2-1.8.2-fabric.jar
  [✔️] freecam-1.1.2+1.18.jar
  [✔️] geckolib-fabric-1.18-3.0.52.jar
  [✔️] grounded_origins-fabric-1.18.2-1.2.0.jar
  [✔️] illuminations-1.10.4.jar
  [✔️] immersive-portals-1.4.9-mc1.18.2-fabric (1).jar
  [✔️] indium-1.0.6+mc1.18.2.jar
  [✔️] infusion-table-mod-1.1.0 (1).jar
  [✔️] interactic-0.1.10+1.18.jar
  [✔️] iris-mc1.18.2-1.2.6(1).jar
  [✔️] itemscroller-fabric-1.18.2-0.16.0.jar
  [✔️] krypton-0.1.9.jar
  [✔️] lambdynamiclights-2.1.0+1.17 (1).jar
  [✔️] lazydfu-0.1.2.jar
  [✔️] LibraryFerret-Fabric-1.18.2-2.5.0.jar
  [✔️] malilib-fabric-1.18.2-0.12.1.jar
  [✔️] mavm-fabric-1.18.1-1.0.7a.jar
  [✔️] mcw-bridges-2.0.3fabric-mc1.18.2.jar
  [✔️] mcw-doors-1.0.6fabric-mc1.18.2.jar
  [✔️] mcw-fences-1.0.6fabric-mc1.18.2.jar
  [✔️] mcw-lights-1.0.4fabric-mc1.18.2.jar
  [✔️] mcw-paintings-1.0.3fabric-mc1.18.2.jar
  [✔️] mcw-paths-1.0.0fabric-mc1.18.2.jar
  [✔️] mcw-roofs-2.1.2fabric-mc1.18.2.jar
  [✔️] mcw-trapdoors-1.0.6fabric-mc1.18.2.jar
  [✔️] mcw-windows-2.0.3bfabric-mc1.18.2.jar
  [✔️] moborigins-1.8.1.jar
  [✔️] modmenu-3.2.3.jar
  [✔️] Mo-Glass-1.6.1-MC1.18.2.jar
  [✔️] naturalist-fabric-1.0.4-1.18.2.jar
  [✔️] NE-1.18-Fabric-1.4.0.jar
  [✔️] notenoughcrashes-4.1.6+1.18.2-fabric.jar
  [✔️] Origins-1.18.2-1.4.1.jar
  [✔️] Origins-Classes-1.18.2-1.3.0.jar
  [✔️] Patchouli-1.18.2-71.1-FABRIC.jar
  [✔️] Pehkui-3.3.3+1.14.4-1.19.1.jar
  [✔️] plushie-mod-1.2-1.18.2.jar
  [✔️] polymorph-fabric-0.0.21-1.18.2 (1).jar
  [✔️] reeses_sodium_options-1.4.4+mc1.18.2-build.46.jar
  [✔️] rocks-1.6.0.jar
  [✔️] RoughlyEnoughItems-8.3.519.jar
  [✔️] RoughlyEnoughProfessions-fabric-1.18.2-1.0.1.jar
  [✔️] SimpleBackpack_Fabric-1.18.2-1.2.37.jar
  [✔️] SimpleRPC-fabric-1.18.2-3.1.1.jar
  [✔️] Soaring-Structures-2-1.18.2-2.3.1-FABRIC.jar
  [✔️] sodium-extra-0.4.6+mc1.18.2-build.46.jar
  [✔️] sodium-fabric-mc1.18.2-0.4.1+build.15 (2).jar
  [✔️] soundphysics-fabric-1.18.2-1.0.6.jar
  [✔️] starlight-1.0.2+fabric.89b8d9f.jar
  [✔️] TooManyOrigins-1.18.2-0.5.1.jar
  [✔️] valley-craft-2.3.1-1.18.2.jar
  [✔️] villager-hats-1.4.0.jar
  [✔️] villagernames-1.18.2-4.0.4.jar
  [✔️] voicechat-fabric-1.18.2-2.2.49.jar
  [✔️] wanderingcollector-1.1.2+mc1.18.2.jar
  [✔️] WI-Zoom-1.4-MC1.18.2 (1).jar
  [✔️] wraith-waystones-2.5.5+mc1.18.2.jar
  [✔️] wthit-fabric-4.11.0.jar
  [✔️] Xaeros_Minimap_22.13.0_Fabric_1.18.2.jar
  [✔️] XaerosWorldMap_1.26.2_Fabric_1.18.2.jar

**Comment by Sheep7798** [comment]
You have to tweak the pump range in the settings to make it contiunous

**Comment by RedWideWeb** [comment]
> You have to tweak the pump range in the settings to make it contiunous

So how exactly? Do I reduce it or increase?

**Comment by RedWideWeb** [comment]
Can confirm that I also have this issue

**Comment by 404Mate** [comment]
Found out this was an issue with the config not allowing infinite sources. Fixed it

**Comment by 404Mate** [comment]
It is still an issue. Cant figure out what it is but its draining the nether when infinite sources should be allowed

**Comment by 404Mate** [comment]
After attempting to pump for longer I get a ticking block crash on the pump. Log here

https://gist.github.com/404Mate/db78f8d1a40c7ac288a1fde99f2c0281

**Comment by RedWideWeb** [comment]
> Found out this was an issue with the config not allowing infinite sources. Fixed it

I mean if you look closely to the nether ocean it is obvious because it starts draining lava sources from 30 blocks away so infinite sources don’t clearly don’t work. And the lag is probably due to an algorithm selecting random block to drain in an enormous ocean

**Comment by RedWideWeb** [comment]
Female Boobs mod 😏😏😏

**Comment by 404Mate** [comment]
was supposed to be fixed upstream with 0.5c, still having the same issue on fabric
https://github.com/Creators-of-Create/Create/issues/3615

**Comment by TropheusJ** [comment]
can this be tested with a [dev build](https://github.com/Fabricators-of-Create/Create/actions/runs/2950338012)?

**Comment by 404Mate** [comment]
Will hopefully test tonight and i'll let you know

**Comment by 404Mate** [comment]
Tested with the latest dev build with a friend. tested it in a singleplayer creative instance with most of the mods from the server. lava pumping is still slow since it keeps resetting and is not infinite but we pumped over 200 buckets and did not have the crash.

**Comment by AurySystem** [comment]
We should note, the water ocean in the overworld also is not infinite, but due to it starting and stopping because of the size of the ocean it doesn't surpress block updates and refills itself.

Also this is definitely working upstream and is only currently a bug with the fabric port.

**Comment by TropheusJ** [comment]
Are you on 0.5d? Update suppression should be fixed.

**Comment by AurySystem** [comment]
0.5d-731
Update suppression breaks because the pumping is non-continuous even with a stable powering.
Whenever the pulley shuts off when pumping from a source that's too big it seems to cancel the update suppression until it restarts. Which seems to happen about once a second.
Noticeable way to recreate this is to have a small square of water source blocks directly above the ocean you attempt to drain, in the rare case the pump gets far enough to actually bucket one of them block update suppression immediately breaks.

Our theory is that on large sources that should be considered bottomless, but the bottomless check doesn't work on for some reason, if there's a certain number of fluid sources in range it'll keep recalculating the range and shut off after pumping and then restart and repeat

**Comment by Neubulae** [comment]
Can confirm that this still happens on a previous dev build later than 0.5.0d, will test the latest dev
Edit: With build 2efc3ef, it still workn't
