### ISSUE TITLE
Crash with NBT Crafting

### ISSUE THREAD

**Issue by digitaltrucker** [Fabricators-of-Create/Create#596]
### Describe the Bug

Trying to hand crank a mechanical press crashes the game.  Trying to reload the world afterwards crashes the game.

### Reproduction Steps

1.  Place mechanical press, basin, and hand crank to make iron sheets.
2.  Use it.
3.
...

### Expected Result

Game doesn't crash and world doesn't become unloadable.

### Crash Report or Log

https://pastebin.com/q83bt0uQ

### Operating System

Windows 10

### Mod Version

0.5.0f

### Minecraft Version

1.19.2

### Other Mods

- advanced-xray-fabric 1.19-1.1.0-build.12
- animal_feeding_trough 1.0.3+1.19.2
- architectury 6.3.49
- armorposer 1.2.0
- autofish 0.9.5-SNAPSHOT
- balm-fabric 4.5.2+0
- bedspreads 6.0.0+1.19.2
- beenfo 1.19.1-fabric0.58.5-1.3.3
- betterf3 4.0.0
- bitsandchisels 2.7.0
- cherishedworlds 6.0.1+1.19.2
- ciif 1.0.0+1.19
- cleancut 1.19.2-5.1-fabric
- clienttweaks 8.1.0- cloth-config 8.2.88
- collective-fabric 5.16
- companion 3.0.0
- completeconfig 2.1.0
- continuity 2.0.1+1.19
- create 0.5.0f-776
- customizableelytra 1.6.2-1.19
- debugify 2.8.0
- doubledoors-fabric 3.8
- emi 0.4.2+1.19
- enchantedshulkers 1.0.4
- enchantinginfuser 4.2.2
- endportalcraft 1.1.0
- fabric-api 0.66.0+1.19.2
- fabric-loot-tables-v1 1.1.10+9e7660c690 via fabric-api
- fabric-transitive-access-wideners-v1 1.3.1+42d99c3290 via fabric-api
- fabrication 3.1.3+1.19
- fabricloader 0.14.10
- faster_entity_animations 1.5.6
- forgeconfigapiport 4.2.6
- gildedarmor 1.5.0+fabric-1.19
- guardvillagers 1.19.2-1.0.16
- herdspanic 1.0.6
- horsestatsvanilla 4.2.2
- immersive_portals 2.2.5
- indium 1.0.9+mc1.19.2
- interactic 0.1.11+1.19
- iris 1.4.1
- java 17
- kiwi 8.1.2
- krypton 0.2.1
- lambdynlights 2.1.2+1.19
- lazydfu 0.1.3
- lightoverlay 7.0.0
- litematica 0.12.4
- litematicatool 1.0.0
- lithium 0.10.2
- lootr 0.4.22.61
- malilib 0.13.0
- memoryleakfix 1.19.1-0.7.0
- minecraft 1.19.2
- mixin-conflict-helper 1.2.0
- modmenu 4.1.0
- moreculling 1.19.1-0.10.0
- mousetweaks 2.22
- mzojpaint 1.0.0
- netherportalfix 10.0.0
- nochatreports 1.19.2-v1.13.12
- notenoughanimations 1.6.2
- polymorph 0.45.0+1.19.2
- presencefootsteps 1.6.3
- puzzleslib 4.3.12
- raised 1.1.4
- randomblockplacement 1.19.1-fabric0.58.5-1.1.4
- reeses-sodium-options 1.4.7+mc1.19.2-build.59
- replaymod 1.19.1-2.6.8
- rpg-hud 3.9.4
- seasons 1.4-BETA+1.19
- shulkerboxtooltip 3.2.2+1.19.2
- skinned_lanterns 2.0.0
- sleepwarp 1.2.0+1.19
- sodium 0.4.4+build.18
- sodium-extra 0.4.12+mc1.19.2-build.72
- sound_physics_remastered 1.19.2-1.0.14
- spyglass-improvements 1.4+mc1.19+fabric
- starlight 1.1.1+fabric.ae22326
- wandering_collector 1.1.3+mc1.19
- wilderwild 1.1.1-Fabric+1.19.2
- wiredredstone 0.4.8+1.19
- worldedit 7.2.12+6240-87f4ae1
- worldeditcui 1.19.2+01
- xaeroworldmap 1.28.0

### Additional Context

Using release version of Create (build 776).

**Comment by TropheusJ** [comment]
Try removing NBT Crafting

**Comment by digitaltrucker** [comment]
That worked.  Sadly, NBT Crafting is loaded via Wilder Wild, so that's the mod conflict.  Naturally, removing that mod at this point wrecks the world anyway...

**Comment by SplendidAlakey** [comment]
Sprice Of Fabric also ships NBT Crafting, though, thankfully, that one is easily removed with no consequences.

~~Also, how did you even come up with an idea to try and press something in a basin, lol?~~

Ahhh, you press 9 pieces into blocks that way, didn't know!

**Comment by digitaltrucker** [comment]
Do you think this world will be playable in the future after a bugfix or is it perma-toast?

**Comment by SplendidAlakey** [comment]
I was able to load into my world after crashing the way you described, when I removed NBT Crafting. So I assume the basin press doesn't corrupt anything on its own. Just don't remove neither Create nor Wilder Wild, while loading the world.

**Comment by digitaltrucker** [comment]
NBT Crafting is loaded via Wilder Wild though, it's not a discrete mod.  How do I remove it without removing Wilder Wild?

**Comment by SplendidAlakey** [comment]
Since you asked about "the future after a bugfix", I meant exactly that - whenever the issue gets fixed, the world should load just fine. Until then, don't try loading it without Create or WW.

Out of curiosity, you could try opening WW with an archive manager and removing NBT Crafting from JiJ, but it's very likely to cause a crash and potentially corrupt something anyway. I have no idea what they use the mod for, so I don't recommend doing it.

**Comment by TeaJeep** [comment]
Updating Create to 0.5.0g and WilderWild to 1.1.2 resolved this for me.  I presume the Create update fixed this?  Specifically for me, though, the issue started when I tried to make brass in a basin, unrelated to a hand crank or press.

**Comment by SplendidAlakey** [comment]
> the issue started when I tried to make brass in a basin, unrelated to a hand crank or press.

That was a different issue. Hand cranking above a basin still causes a crash with NBT Crafting.

**Comment by TeaJeep** [comment]
Oh! My bad then, sorry for the misunderstanding!

**Comment by digitaltrucker** [comment]
Yep, issue is resolved as far as I can tell :)

**Comment by SplendidAlakey** [comment]
Huh? I'm going to double check, but at least with Spice Of Fabric it wasn't resolved. Maybe I need to add an updated standalone NBT Crafting...

**Comment by SplendidAlakey** [comment]
Oh, yeah, it is fixed. Just had to update NBT Crafting separately. Sorry, TeaJeep, for the confusion.
