### ISSUE TITLE
Iron nuggets missing from recipes depending on mods installed

### ISSUE THREAD

**Issue by briansemrau** [Fabricators-of-Create/Create#689]
### Describe the Bug

Depending on the mods I have installed, some recipes will be missing items or no longer work. This is not due to an incompatibility, but likely due to some race condition or nondeterministic ordering.

It is likely that recipes with iron nuggets are not the only ones affected.

Here are some example configurations to demonstrate the nondeterministic nature of this bug:

A. ❌Recipes broken
Create (0.5.0g-796+1.19.2)
Quilted Fabric API (4.0.0-beta.24+0.68.0-1.19.2)

B. ✔Recipes work
Create (0.5.0g-796+1.19.2)
Fabric API (0.68.0+1.19.2)

C. ❌Recipes broken
Create (0.5.0g-796+1.19.2)
Fabric API (0.68.0+1.19.2)
Roughly Enough Items (9.1.577)
Architectury (6.3.56)
Cloth Config v8 (8.2.88)
Mod Menu (4.1.1)

D. ❌Recipes broken
Create (0.5.0g-796+1.19.2)
Fabric API (0.68.0+1.19.2)
AppleSkin (2.4.1+mc1.19)

E. ✔Recipes work
Create (0.5.0g-796+1.19.2)
Fabric API (0.68.0+1.19.2)
AppleSkin (2.4.1+mc1.19)
Clear Despawn (1.1.10)
Cloth Config v8 (8.2.88)

### Reproduction Steps

See example mod installation configurations above

1. install mods
2. try to craft Create recipes using iron nuggets
3. may or may not work

### Expected Result

Recipes should always be correct.

### Screenshots and Videos

Andesite alloy
![image](https://user-images.githubusercontent.com/6376721/208269018-b2f21c41-46e4-4b2e-a991-2b5702165754.png)

Encased chain drive
![image](https://user-images.githubusercontent.com/6376721/208269031-47f2a453-7f0a-4b26-a799-b344644a4816.png)

### Crash Report or Log

Logs where recipes work:
https://gist.github.com/briansemrau/6d0011b8d7b56fb49e5d62be3f2a6cbf

Logs where recipes do _not_ work:
https://gist.github.com/briansemrau/1c5eab0e4f2cdacf33a59bc4337977c7

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

See above.

**Comment by briansemrau** [comment]
I was able to solve this by deleting
`create-fabric-0.5.0g-796+1.19.2.jar\META-INF\jars\Registrate-1.1.44-MC1.19.2.jar\META-INF\jars\tags-2.0.588+1.19.2.jar`

I believe this may have already been fixed by this commit: https://github.com/Fabricators-of-Create/Create/commit/88afd924f068cef53eb438dec648daf360969204

**Comment by piebaker** [comment]
Just confirming this bug is still present. @briansemrau What was your fix exactly? I can't seem to find the .jar file you refer to

**Comment by briansemrau** [comment]
It's already been fixed by the commit linked above. The mod just needed an updated release, which has since been posted.
